// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2DxUMhswYR8a7lIq8ILXGp2Va-fVJz6g',
    appId: '1:815075731315:web:417551e3a01203fe490706',
    messagingSenderId: '815075731315',
    projectId: 'diary-5959e',
    authDomain: 'diary-5959e.firebaseapp.com',
    storageBucket: 'diary-5959e.appspot.com',
    measurementId: 'G-S8GC7LQGNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8nptAjR-8kT7J93ZmVuWDwMK4V5NW2Xg',
    appId: '1:815075731315:android:f885d0552a5b243f490706',
    messagingSenderId: '815075731315',
    projectId: 'diary-5959e',
    storageBucket: 'diary-5959e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZCCLFblI1dwA2ClW3cRcQNXOEoNmWL-I',
    appId: '1:815075731315:ios:645e46aed07d2423490706',
    messagingSenderId: '815075731315',
    projectId: 'diary-5959e',
    storageBucket: 'diary-5959e.appspot.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZCCLFblI1dwA2ClW3cRcQNXOEoNmWL-I',
    appId: '1:815075731315:ios:6b38322918eb14e1490706',
    messagingSenderId: '815075731315',
    projectId: 'diary-5959e',
    storageBucket: 'diary-5959e.appspot.com',
    iosBundleId: 'com.example.diaryApp.RunnerTests',
  );
}
